"""Load the CDR scheduled jobs into a fresh database table.

Wipes out any previous jobs from the database. Uses the output
generated by `dump-scheduled-jobs.py --json`.
"""

from json import load
from sys import stdin
from cdrapi import db

INSERT = """\
INSERT INTO scheduled_job (name, enabled, job_class, opts, schedule)
     VALUES (?, ?, ?, ?, ?)"""

jobs = load(stdin)
conn = db.connect()
cursor = conn.cursor()
try:
    cursor.execute("DROP TABLE scheduled_job")
    conn.commit()
except Exception:
    pass
cursor.execute("""\
CREATE TABLE scheduled_job (
          id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
        name NVARCHAR(512) NOT NULL,
     enabled BIT NOT NULL,
   job_class NVARCHAR(128) NOT NULL,
        opts VARCHAR(1024) NOT NULL,
    schedule VARCHAR(256) NULL
)""")
cursor.execute("GRANT SELECT ON scheduled_job TO CdrGuest")
for values in jobs:
    cursor.execute(INSERT, values)
conn.commit()
