#!/usr/bin/python

#####################################################################
# make-cdr-doc
#
# Generate PDF for all of the CDR system documentation, using the
# UNIX/Linux "htmldoc" program.
#
# make-cdr-doc resides on our "verdi" Linux server in /usr/local/bin,
# but is stored in CVS under /cdr/Utilities.
#
#                                   Author: Bob Kline
#####################################################################

import os, re, sys, time, urllib

class Book:
    def __init__(self, url, name, title, body):
        self.url   = url
        self.name  = name
        self.title = title
        self.body  = body
    def create(self):
        htmlname = "%s.html" % self.name
        bookname = "%s.book" % self.name
        pdfname  = "%s.pdf" % self.name
        file     = open(htmlname, "w")
        file.write("""\
<html>
 <head>
  <title>%s</title>
  <meta name='author' content='CIPS'>
  <meta name='subject' content='%s'>
  <meta name='copyright' content='%s'>
 </head>
 <body>
  <center>
   <font color='black'>
    <h1>%s</h1>
    <br />
    %s    
   </font>
  </center>
 </body>
</html>
""" % (self.title, self.title, time.strftime("%Y %d, %Y"), self.title,
       self.body))
        file.close()
        urlobj  = urllib.urlopen(self.url)
        page    = urlobj.read()
        file    = open(bookname, 'w')
        file.write("""\
#HTMLDOC
-f %s -t pdf --color --charset iso-8859-1 --size Letter \\
--footer c.1 --titlefile %s --title -v --book \\
--textcolor black --fontsize 12 --linkstyle plain --linkcolor maroon \\
--bodyfont %s
%s
""" % (pdfname, htmlname, font, htmlname))
        for match in pattern.findall(page):
            file.write("http://bach.nci.nih.gov/cgi-bin/cdr/Filter.py?"
                       "DocId=%s&Filter=name:Documentation+Help+Files+"
                       "Filter\n" % match)
        file.close()
        file = os.popen('htmldoc --batch %s' % bookname)
        print file.read()
        print ("exit code: %s" % file.close())

pattern = re.compile('/cgi-bin/cdr/Filter.py\\?DocId=(CDR\\d+)')
font    = len(sys.argv) > 1 and sys.argv[1] or "Times"
base    = 'http://bach.nci.nih.gov/cgi-bin/cdr/Help.py?Session=guest'
books   = (Book(base + "&flavor=CDR+Help", "CdrUserGuide",
                "CDR User Guide", """\
    <p>Guide to the use of the CIPS Central Data Repository</p>
    <p>National Cancer Institute</p>"""),
           Book(base + "&flavor=System", "CdrSystemDocs",
                "CDR System Documentation", """\
    <p>System-level documentation for the CIPS Central Data Repository</p>
    <p>National Cancer Institute</p>"""),
           Book(base + "&flavor=Operating", "CdrOpsManual",
                "CDR Operations Manual", """\
    <p>Operations guide for the CIPS Central Data Repository</p>
    <p>National Cancer Institute</p>"""))
    
urls    = (base, base + "&flavor=System", base + "&flavor=Operating")
names   = ("CdrUserGuide", "CdrSystemDocs", "CdrOpsManual")
titles  = ("CDR User Guide", "CDR Systems Guide", "CDR Operations Manual")
for book in books:
    book.create()
